fix: copy cell only on cells
qlik-oss/sn-table pull request #881
Opened 2023-03-03 15:43 UTC by a-m-dev

only show copy cell value in context menu in 'TD' and 'TH' elements

2023-03-03 20:11 UTC, LiKang6688 commented
LGTM, shall we add an integration test with React-Testing-Library?

2023-03-06 06:40 UTC, cbt1 requested changes
Does not work in virtual scroll table. Table element is not used there. You will need to check something like a class name

2023-03-06 08:19 UTC, haxxmaxx commented on src/nebula-hooks/use-context-menu.ts
> +      tagNamesWhiteList.has(event.target.closest('.sn-table-cell')?.tagName) &&
I think the class should be enough, all cells should have it

2023-03-07 15:05 UTC, haxxmaxx approved these changes

2023-03-07 16:32 UTC, LiKang6688 approved these changes

2023-03-08 08:17 UTC, cbt1 approved these changes

2023-03-08 08:17 UTC, merged